#!/bin/sh
# postinst script for RhythmCat2
#
# see: dh_installdeb(1)

set -e

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

if test -x /usr/bin/update-menus; then
    update-menus
fi

exit 0
