/*
 * RhythmCat UI CSS Data Declaration
 *
 * rc-ui-css.h
 * This file is part of RhythmCat Music Player (GTK+ Version)
 *
 * Copyright (C) 2012 - SuperCat, license: GPL v3
 *
 * RhythmCat is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * RhythmCat is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with RhythmCat; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, 
 * Boston, MA  02110-1301  USA
 */

#ifndef HAVE_RC_UI_CSS_H
#define HAVE_RC_UI_CSS_H

gchar rc_ui_css_monochrome[] = 
    "@define-color rc_base_color #4f524f;\n"
    "@define-color rc_bg_color #363b3b;\n"
    "@define-color rc_text_color #eeeeec;\n"
    "@define-color rc_fg_color @rc_text_color;\n"
    "@define-color rc_borders #24282a;\n"
    "@define-color rc_selected_bg_color #3465a4;\n"
    "@define-color rc_selected_fg_color @rc_text_color;\n"
    "@define-color rc_unfocused_base_color @rc_base_color;\n"
    "@define-color rc_unfocused_text_color mix(@rc_unfocused_base_color, @rc_text_color, 0.8);\n"
    "@define-color rc_unfocused_fg_color mix(@rc_unfocused_bg_color, @rc_text_color, 0.3);\n"
    "@define-color rc_unfocused_bg_color @rc_bg_color;\n"
    "@define-color rc_unfocused_selected_bg_color @unfocused_borders;\n"
    "@define-color rc_unfocused_selected_fg_color @rc_selected_fg_color;\n"
    "@define-color rc_insensitive_bg_color alpha(#0b0b0d, 0.0);\n"
    "@define-color rc_insensitive_fg_color alpha(#717171, 0.50);\n"
    "@define-color rc_insensitive_border_color alpha(#717171, 0.50);\n"
    "@define-color rc_scrollbar_trough shade(@rc_bg_color, 1.2);\n"
    "@define-color rc_scrollbar_trough_insensitive shade(@rc_bg_color, 1.05);\n"
    "@define-color rc_scrollbar_trough shade(@rc_unfocused_bg_color, 1.2);\n"
    "@define-color rc_scrollbar_slider mix(@rc_scrollbar_trough, @rc_fg_color, 0.5);\n"
    "@define-color rc_scrollbar_slider_prelight mix(@rc_scrollbar_trough, @rc_fg_color, 0.7);\n"
    "@define-color rc_scrollbar_slider_active @rc_selected_bg_color;\n"
    "@define-color rc_scrollbar_slider_insensitive alpha(black, 0);\n"
    "@define-color rc_scrollbar_slider_unfocused shade(@rc_unfocused_base_color, 0.8);\n"
    "@define-color rc_scale_fill shade (@rc_insensitive_border_color, 0.90);\n"
    "@define-color rc_scale_progress_fill #2c85e2;\n"
    "@define-color rc_button_gradient_color_a shade (@rc_bg_color, 1.1);\n"
    "@define-color rc_button_gradient_color_b shade (@rc_bg_color, 0.9);\n"
    "@define-color rc_button_hover_gradient_color_a shade (@rc_button_gradient_color_a, 1.10);\n"
    "@define-color rc_button_hover_gradient_color_b shade (@rc_button_gradient_color_b, 1.02);\n"
    "@define-color rc_button_active_gradient_color_a shade (@rc_button_gradient_color_b, 0.7);\n"
    "@define-color rc_button_active_gradient_color_b shade (@rc_button_gradient_color_a, 0.7);\n"
    "#RC2MainWindow.background\n"
    "{\n"
    "    background-color: @rc_bg_color;\n"
    "    background-image: none;\n"
    "}\n"
    "#RC2MainWindow #RC2TitleLabel,\n"
    "#RC2MainWindow #RC2ArtistLabel,\n"
    "#RC2MainWindow #RC2AlbumLabel,\n"
    "#RC2MainWindow #RC2InfoLabel,\n"
    "#RC2MainWindow #RC2LengthLabel,\n"
    "#RC2MiniWindow GtkLabel\n"
    "{\n"
    "    color: @rc_text_color;\n"
    "    font: Cantarell, Dejavu Sans\n"
    "}\n"
    "#RC2MainWindow #RC2TimeLabel\n"
    "{\n"
    "    color: #6CD02F;\n"
    "    font: Cantarell, Dejavu Sans\n"
    "}\n"
    "#RC2MainWindow #RC2Lyric1ScrollableLabel,\n"
    "#RC2MainWindow #RC2Lyric2ScrollableLabel\n"
    "{\n"
    "    background-color: @rc_bg_color;\n"
    "    background-image: none;\n"
    "    color: @rc_text_color;\n"
    "    font: Cantarell, Dejavu Sans\n"
    "}\n"
    "#RC2MainWindow RCUiSpectrumWidget#RC2SpectrumWidget\n"
    "{\n"
    "    background-color: @rc_bg_color;\n"
    "    background-image: none;\n"
    "    color: #00A0F0;\n"
    "}\n"
    "#RC2MainWindow #RC2ListPaned\n"
    "{\n"
    "    background-color: @rc_base_color;\n"
    "    background-image: none;\n"
    "}\n"
    "#RC2MainWindow #RC2ListPaned:prelight\n"
    "{\n"
    "    background-color: shade(@rc_base_color, 1.3);\n"
    "    background-image: none;\n"
    "}\n"
    "#RC2MainWindow #RC2ListPaned:active\n"
    "{\n"
    "    background-color: shade(@rc_base_color, 1.1);\n"
    "    background-image: none;\n"
    "}\n"
    "#RC2MainWindow #RC2CatalogScrolledWindow\n"
    "{\n"
    "    background-color: @rc_bg_color;\n"
    "    background-image: none;\n"
    "}\n"
    "#RC2MainWindow #RC2CatalogScrolledWindow.frame\n"
    "{\n"
    "    border-style: solid;\n"
    "    border-color: @rc_borders;\n"
    "    border-width: 1px;\n"
    "    border-radius: 2;\n"
    "    padding: 0;\n"
    "}\n"
    "#RC2MainWindow #RC2CatalogScrolledWindow .scrollbar,\n"
    "#RC2MainWindow #RC2PlaylistScrolledWindow .scrollbar\n"
    "{\n"
    "    background-image: none;\n"
    "    border-style: solid;\n"
    "    -GtkRange-trough-border: 0;\n"
    "    -GtkScrollbar-has-backward-stepper: false;\n"
    "    -GtkScrollbar-has-forward-stepper: false;\n"
    "    -GtkRange-slider-width: 13;\n"
    "    -GtkScrollbar-min-slider-length: 42;\n"
    "    -GtkRange-stepper-spacing: 0;\n"
    "    -GtkRange-trough-under-steppers: 1;\n"
    "}\n"
    "#RC2MainWindow #RC2CatalogScrolledWindow .scrollbars-junction,\n"
    "#RC2MainWindow #RC2CatalogScrolledWindow .scrollbar.trough,\n"
    "#RC2MainWindow #RC2PlaylistScrolledWindow .scrollbars-junction,\n"
    "#RC2MainWindow #RC2PlaylistScrolledWindow .scrollbar.trough\n"
    "{\n"
    "    background-image: none;\n"
    "    background-color: @rc_scrollbar_trough;\n"
    "    border-width: 0;\n"
    "    border-radius: 0;\n"
    "    border-image: none;\n"
    "}\n"
    "#RC2MainWindow #RC2CatalogScrolledWindow .scrollbar.button,\n"
    "#RC2MainWindow #RC2CatalogScrolledWindow .scrollbar.button:active,\n"
    "#RC2MainWindow #RC2CatalogScrolledWindow .scrollbar.button:active:hover,\n"
    "#RC2MainWindow #RC2CatalogScrolledWindow .scrollbar.button:insensitive,\n"
    "#RC2MainWindow #RC2PlaylistScrolledWindow .scrollbar.button,\n"
    "#RC2MainWindow #RC2PlaylistScrolledWindow .scrollbar.button:active,\n"
    "#RC2MainWindow #RC2PlaylistScrolledWindow .scrollbar.button:active:hover,\n"
    "#RC2MainWindow #RC2PlaylistScrolledWindow .scrollbar.button:insensitive\n"
    "{\n"
    "    border-style: none;\n"
    "    border-image: none;\n"
    "    border-radius: 0;\n"
    "    background-image: none;\n"
    "    background-color: transparent;\n"
    "}\n"
    "#RC2MainWindow #RC2CatalogScrolledWindow .scrollbar.button:active,\n"
    "#RC2MainWindow #RC2CatalogScrolledWindow .scrollbar.button:active:hover,\n"
    "#RC2MainWindow #RC2PlaylistScrolledWindow .scrollbar.button:active,\n"
    "#RC2MainWindow #RC2PlaylistScrolledWindow .scrollbar.button:active:hover\n"
    "{\n"
    "    background-color: mix(@rc_scrollbar_slider, @rc_scrollbar_trough, 0.8);\n"
    "}\n"
    "#RC2MainWindow #RC2CatalogScrolledWindow .scrollbar.button.top:hover,\n"
    "#RC2MainWindow #RC2PlaylistScrolledWindow .scrollbar.button.top:hover\n"
    "{\n"
    "    box-shadow: 0 -1 inset mix(@rc_scrollbar_slider, @rc_scrollbar_trough, 0.8);\n"
    "}\n"
    "#RC2MainWindow #RC2CatalogScrolledWindow .scrollbar.button.bottom:hover,\n"
    "#RC2MainWindow #RC2PlaylistScrolledWindow .scrollbar.button.bottom:hover\n"
    "{\n"
    "    box-shadow: 0 1 inset mix(@rc_scrollbar_slider, @rc_scrollbar_trough, 0.8);\n"
    "}\n"
    "#RC2MainWindow #RC2CatalogScrolledWindow .scrollbar.button.right:hover,\n"
    "#RC2MainWindow #RC2PlaylistScrolledWindow .scrollbar.button.right:hover\n"
    "{\n"
    "    box-shadow: 1 0 inset mix(@rc_scrollbar_slider, @rc_scrollbar_trough, 0.8);\n"
    "}\n"
    "#RC2MainWindow #RC2CatalogScrolledWindow .scrollbar.button.left:hover,\n"
    "#RC2MainWindow #RC2PlaylistScrolledWindow .scrollbar.button.left:hover\n"
    "{\n"
    "    box-shadow: -1 0 inset mix(@rc_scrollbar_slider, @rc_scrollbar_trough, 0.8);\n"
    "}\n"
    "#RC2MainWindow #RC2CatalogScrolledWindow .scrollbar.button,\n"
    "#RC2MainWindow #RC2PlaylistScrolledWindow .scrollbar.button\n"
    "{\n"
    "    color: @rc_scrollbar_slider;\n"
    "}\n"
    "#RC2MainWindow #RC2CatalogScrolledWindow .scrollbar.button:hover,\n"
    "#RC2MainWindow #RC2PlaylistScrolledWindow .scrollbar.button:hover\n"
    "{\n"
    "    color: @rc_scrollbar_slider_prelight;\n"
    "}\n"
    "#RC2MainWindow #RC2CatalogScrolledWindow .scrollbar.button:insensitive,\n"
    "#RC2MainWindow #RC2PlaylistScrolledWindow .scrollbar.button:insensitive\n"
    "{\n"
        "color: mix(@rc_scrollbar_slider, @rc_scrollbar_trough, 0.6);\n"
    "}\n"
    "#RC2MainWindow #RC2CatalogScrolledWindow .scrollbar.button:active,\n"
    "#RC2MainWindow #RC2PlaylistScrolledWindow .scrollbar.button:active\n"
    "{\n"
    "    color: @rc_scrollbar_slider_active;\n"
    "}\n"
    "#RC2MainWindow #RC2CatalogScrolledWindow .scrollbar.trough.vertical,\n"
    "#RC2MainWindow #RC2PlaylistScrolledWindow .scrollbar.trough.vertical\n"
    "{\n"
    "       box-shadow: -1 0 inset alpha(@rc_text_color, 0.05), 1 0 inset alpha(@rc_text_color, 0.1);\n"
    "}\n"
    "#RC2MainWindow #RC2CatalogScrolledWindow .scrollbar.trough.horizontal,\n"
    "#RC2MainWindow #RC2PlaylistScrolledWindow .scrollbar.trough.horizontal\n"
    "{\n"
    "   box-shadow: 0 -1 inset alpha(@rc_text_color, 0.05), 0 1 inset alpha(@rc_text_color, 0.1);\n"
    "}\n"
    "#RC2MainWindow #RC2CatalogScrolledWindow .scrollbar.trough:insensitive,\n"
    "#RC2MainWindow #RC2PlaylistScrolledWindow .scrollbar.trough:insensitive\n"
    "{\n"
    "    background-color: @rc_scrollbar_trough_insensitive;\n"
    "    border-style: solid;\n"
    "    border-image: none;\n"
    "    border-color: transparent;\n"
    "    border-width: 3px;\n"
    "}\n"
    "#RC2MainWindow #RC2CatalogScrolledWindow .scrollbar.slider,\n"
    "#RC2MainWindow #RC2PlaylistScrolledWindow .scrollbar.slider\n"
    "{\n"
    "    background-image: none;\n"
    "    background-color: @rc_scrollbar_slider;\n"
    "    border-radius: 6;\n"
    "    border-style: solid;\n"
    "    border-image: none;\n"
    "    border-color: transparent;\n"
    "    border-width: 3px;\n"
    "}\n"
    "#RC2MainWindow #RC2CatalogScrolledWindow .scrollbar.slider:hover,\n"
    "#RC2MainWindow #RC2PlaylistScrolledWindow .scrollbar.slider:hover\n"
    "{\n"
    "    transition: 1000ms linear;\n"
    "    background-image: none;\n"
    "    background-color: @rc_scrollbar_slider_prelight;\n"
    "    border-style: solid;\n"
    "    border-image: none;\n"
    "    border-color: transparent;\n"
    "    border-width: 3px;\n"
    "}\n"
    "#RC2MainWindow #RC2CatalogScrolledWindow .scrollbar.slider:prelight:active,\n"
    "#RC2MainWindow #RC2PlaylistScrolledWindow .scrollbar.slider:prelight:active\n"
    "{\n"
    "    background-image: none;\n"
    "    background-color: @rc_scrollbar_slider_active;\n"
    "    border-style: solid;\n"
    "    border-image: none;\n"
    "    border-color: transparent;\n"
    "    border-width: 3px;\n"
    "}\n"
    "#RC2MainWindow #RC2CatalogScrolledWindow .scrollbar.slider:insensitive,\n"
    "#RC2MainWindow #RC2PlaylistScrolledWindow .scrollbar.slider:insensitive\n"
    "{\n"
    "    background-color: @rc_scrollbar_slider_insensitive;\n"
    "    border-style: solid;\n"
    "    border-image: none;\n"
    "    border-color: transparent;\n"
    "    border-width: 3px;\n"
    "}\n" 
    "#RC2MainWindow #RC2CatalogListView,\n"
    "#RC2MainWindow #RC2CatalogListView.view,"
    "#RC2MainWindow #RC2PlaylistListView,\n"
    "#RC2MainWindow #RC2PlaylistListView.view\n"
    "{\n"
    "    background-color: @rc_base_color;\n"
    "    background-image: none;\n"
    "    color: @rc_text_color;\n"
    "    font: Cantarell, Dejavu Sans\n"
    "}\n"
    "#RC2MainWindow #RC2CatalogListView.view:selected,\n"
    "#RC2MainWindow #RC2PlaylistListView.view:selected\n"
    "{\n"
    "    background-color: @rc_selected_bg_color;\n"
    "    background-image: none;\n"
    "    color: @theme_selected_fg_color;\n"
    "}\n"
    "#RC2MainWindow #RC2CatalogListView:insensitive,\n"
    "#RC2MainWindow #RC2CatalogListView.view:insensitive,\n"
    "#RC2MainWindow #RC2PlaylistListView:insensitive,\n"
    "#RC2MainWindow #RC2PlaylistListView.view:insensitive\n"
    "{\n"
    "    background-color: @rc_insensitive_bg_color;\n"
    "    background-image: none;\n"
    "    color: @rc_insensitive_fg_color;\n"
    "}\n"
    "#RC2MainWindow #RC2CatalogListView.view:prelight,\n"
    "#RC2MainWindow #RC2PlaylistListView.view:prelight\n"
    "{\n"
    "    background-color: shade(@rc_base_color, 0.8);\n"
    "    background-image: none;\n"
    "    color: @theme_selected_fg_color;\n"
    "}\n"
    "#RC2MainWindow #RC2TimeScale\n"
    "{\n"
    "    -GtkScale-slider-length: 16;\n"
    "    -GtkRange-slider-width: 20;\n"
    "    -GtkRange-trough-border: 0;\n"
    "    background-color: @rc_bg_color;\n"
    "}\n"
    "#RC2MainWindow #RC2TimeScale.slider,\n"
    "#RC2MainWindow #RC2TimeScale.slider:hover,\n"
    "#RC2MainWindow #RC2TimeScale.slider:insensitive\n"
    "{\n"
    "    border-width: 0;\n"
    "    border-radius: 0;\n"
    "    border-style: none;\n"
    "    color: alpha(@rc_base_color, 0.0);\n"
    "    background-color: alpha(@rc_base_color, 0.0);\n"
    "}\n"
    "#RC2MainWindow #RC2TimeScale.trough\n"
    "{\n"
    "    border-width: 1;\n"
    "    border-radius: 2;\n"
    "    border-style: solid;\n"
    "    background-color: shade(@rc_scale_fill, 1.5);\n"
    "    background-image: none;\n"
    "    border-color: shade(@rc_insensitive_border_color, 1.5);\n"
    "    border-image: none;\n"
    "}\n"
    "#RC2MainWindow #RC2TimeScale.trough:insensitive\n"
    "{\n"
    "    background-color: @rc_insensitive_bg_color;\n"
    "    background-image: none;\n"
    "    border-image: none;\n"
    "    border-style: solid;\n"
    "    border-color: @rc_insensitive_border_color;\n"
    "}\n"
    "#RC2MainWindow #RC2TimeScale.progressbar\n"
    "{\n"
    "    background-color: @rc_scale_progress_fill;\n"
    "    border-width: 1;\n"
    "    border-radius: 2;\n"
    "    border-style: none;\n"
    "}\n"
    "#RC2MainWindow #RC2TimeScale.mark\n"
    "{\n"
    "    color: shade (@rc_bg_color, 0.56);\n"
    "}\n"
    "#RC2MainWindow #RC2ControlButton.button,\n"
    "#RC2MainWindow #RC2VolumeButton.button\n"
    "{\n"
    "    padding: 1 4;\n"
    "    -GtkWidget-focus-line-width: 2;\n"
    "    -GtkButton-child-displacement-x: 1;\n"
    "    -GtkButton-child-displacement-y: 1;\n"
    "    -GtkButton-image-spacing: 4;\n"
    "    -GtkButton-interior-focus: true;\n"
    "    -GtkButton-default-border: 0;\n"
    "    -GtkButton-inner-border: 0;\n"
    "    color: @rc_text_color;\n"
    "    border-radius: 3;\n"
    "    border-width: 1;\n"
    "    border-style: none;\n"
    "    background-image: -gtk-gradient (linear, left top, left bottom,\n"
    "        from (@rc_button_gradient_color_a),\n"
    "        to (@rc_button_gradient_color_b));\n"
    "}\n"
    "#RC2MainWindow #RC2ControlButton.button:hover,\n"
    "#RC2MainWindow #RC2VolumeButton:hover\n"
    "{\n"
    "    background-image: -gtk-gradient (linear, left top, left bottom,\n"
    "        from (@rc_button_hover_gradient_color_a),\n"
    "        to (@rc_button_hover_gradient_color_b));\n"
    "}\n"
    "#RC2MainWindow #RC2ControlButton.button:active,\n"
    "#RC2MainWindow #RC2ControlButton.button:hover:active,\n"
    "#RC2MainWindow #RC2VolumeButton:active,\n"
    "#RC2MainWindow #RC2VolumeButton.button:hover:active\n"
    "{\n"
    "    background-image: -gtk-gradient (linear, left top, left bottom,\n"
    "        from (@rc_button_active_gradient_color_a),\n"
    "        to (alpha (@rc_button_active_gradient_color_b, 0.13)));\n"
    "}\n"
    "#RC2MainWindow #RC2ControlButton.button:insensitive,\n"
    "#RC2MainWindow #RC2VolumeButton.button:insensitive\n"
    "{\n"
    "    background-image: none;\n"
    "    background-color: @rc_insensitive_bg_color;\n"
    "    color: @rc_insensitive_fg_color;\n"
    "    border-image: none;\n"
    "    border-style: solid;\n"
    "}\n"
    "#RC2MainWindow #RC2ControlButton.button.default,\n"
    "#RC2MainWindow #RC2VolumeButton.button.default\n"
    "{\n"
    "    border-width: 1;\n"
    "}\n"
    "";

#endif

